DROP TABLE IF EXISTS noteful_folders;
DROP TABLE IF EXISTS noteful_notes;

CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_name TEXT NOT NULL,
    content TEXT NOT NULL,
    date_modified DATE
);

CREATE TABLE noteful_folders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folder_name TEXT NOT NULL,
    note_id INTEGER REFERENCES noteful_notes(id),
    date_last_modified DATE
);